### ISSUE TITLE
pretrained된 자료도 꼭 gpu가 필요한가요?

### ISSUE THREAD

**Issue by parkhojun** [tbai2019/HanBert-54k-N#1]
안녕하세요. repo 잘 봤습니다!
제가 cpu를 사용할 수 없는 환경인데, pretrained된 자료도 꼭 gpu가 필요한지 궁금합니다.

**Comment by tbai2019** [comment]
구글에서 배포한 원래의 코드는 GPU없이도 되는 것으로 알고 있는데, 저희가 배포한 코드도 되는지는 테스트해보지 않았습니다. ^^;; 
해보시고 안되면 알려주세요... 
저희는 GPU가 없는 환경이 없어요 ㅠㅠ
