### ISSUE TITLE
python src/mrc_test.py --example_file=korquad.1.0/KorQuAD_v1.0_dev.json 명령어 실행 오류

### ISSUE THREAD

**Issue by parkhojun** [tbai2019/HanBert-54k-N#2]
안녕하세요. HanBert를 보고 감명받아 docker container 내부에서 환경설정을 하고 실행해보기 위해 예제를 보고 진행하고 있습니다. python src/mrc_test.py --example_file=korquad.1.0/KorQuAD_v1.0_dev.json 명령어를 실행하려 하는데 다음과 같은 에러가 뜹니다.

  File "src/mrc_test.py", line 790, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "src/mrc_test.py", line 741, in main
    examples = read_korquad_examples(input_file=FLAGS.example_file)
  File "src/mrc_test.py", line 691, in read_korquad_examples
    input_data = json.load(reader)["data"]
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 122, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py", line 84, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: korquad.1.0/KorQuAD_v1.0_dev.json; No such file or directory

제가 예제를 잘 이해하지 못해서 다음과 같은 에러가 뜨는 것 같습니다.
KorQuAD_v1.0_dev.json같이 따로 받는 파일들은 어디에다가 옮겨놔야 하는지, 아니면 이외에 어떠한 문제가 있는 건지 궁금합니다.
감사합니다.

**Comment by tbai2019** [comment]
프로그램 문제는 아니고, 예제 데이터가 없다는 오류입니다.

> korquad.1.0/KorQuAD_v1.0_dev.json; No such file or directory

korquad.1.0의 데이터 배포 권한이 저희에게 없기 때문에 아래 링크의  korquad.1.0의 페이지에 가셔서 

https://korquad.github.io/category/1.0_KOR.html

좌측 하단의 Getting Started 에 데이터 다운로드를 누르시면 해당 화일(KorQuAD_v1.0_dev.json)을 다운로드 받으실 수 있습니다. 
다운 로드하시고, 적당한 디렉토리 (위의 예제에서는 ./korquad.1.0 디렉토리) 그 화일의 위치를 파라메터로 사용하시면 됩니다. 

아마도 쉽게 해보실 수 있을 겁니다. 성공하시면, 답변으로 올려주세요. (본인이 해보신 과정도 올려주시면, 비슷한 고민이 있는 분들에게 도움이 될 것 같네요)

성공하시기를....

**Comment by parkhojun** [comment]
감사합니다. 추가로 디렉토리 폴더를 만들어주지 않아 생겼던 오류였습니다. :) 코드를 실행하는데 성공했습니다. 그리고  이전에 했던 질문과 같이 독해예제 맛보기 명령어 코드를 돌리는 경우는 CPU환경에서도 상관없이 잘 됩니다ㅎㅎ.
제가 실력이 부족해서 마지막으로 질문드리고 싶은 부분이 있는데, KorQuAD_v1.0_dev.json 이 파일이 기계독해 예문 964건에 대해서만 train된 코드인지, 그리고 이외에 별도의 train과정 없이 다른 독해코드를 돌릴 수 있는 방법이 있는지 궁금합니다.

**Comment by tbai2019** [comment]
^^ 성공을 축하합니다.  특히나 CPU 만으로도 동작이 된다니, 얼마나 느릴까 (아마도 1초 정도?) 싶기는 합니다. 
GPU를 사용하면 GPU의 성능에 따라 다르지만 아마도 1초에 20~100개 정도 대답을 하는 것 같습니다. 

학습 데이터에 대해서는 README 에 써 놓았는데요, (아래)와 같습니다.
여러가지 섞어서 학습을 한 것이기 때문에 답변에 대한 일관성은 떨어집니다. 
특히나 NIA의 데이터가 좀 거시기 합니다. 맛보기로 해보시라고 공개해 드렸습니다.
(이미 독해용 데이터로 학습된 모델이기 때문에)
별도의 추가  train없이 HanBert-54kN-MRC 모델 만으로도 독해를 해볼 수 있겠습니다.
독해는 학습 데이터의 성격에 따라서 그에 맞춰진 답변을 찾아냅니다. 
그래서 학습 데이터의 성격과 품질이 매우 중요합니다.

HanBert-54kN 모델은 순수한 한국어 BERT 모델이므로, KorQuAD_v1.0_train.json으로 학습을 시키고 (epoch를 크게 해서 여러개 생성되는 checkpoint에 KorQuAD_v1.0_dev.json으로 성능평가를 해보면 아마도 최적의 Checkpoint를 찾을 수 있을 것입니다.) 성능을 보시면 되는데, 그것에 대한 내용도 README에 모두 있습니다. 자세히 읽어봐 주세요.

-------

(아래)

> 미리 학습을 시킨 기계 독해 모델로 느껴보실 수 있도록 학습된 모델을 공개합니다.
> Model명 : HanBert-54kN-MRC
> epochs : 3.0
> 학습 데이터가 서로 다른 지침으로 작성되어서 동일한 형식의 질문에 각각 다른 답변의 유형이 존재합니다.
> 학습데이터의 품질에 대해서도 의구심이 있지만, 공개되어 있는 학습데이터를 사용하여 학습하였습니다.
> 문제시 되는 것들 :
> 예 : 어디에서 출발해? A) 부산 B) 부산에서
> 학습 데이터

> HanBert-54kN + 기계독해 학습 데이터 (총 253,466건)
> NIA의 기계독해 데이터 : 162,632건
> KorQuAD 1.0의 데이터 : 66,181건
> KorQuAD 2.0의 데이터 : 24,653건
