### ISSUE TITLE
moran.db의 경로를 수정할 수 없거나, 수정 방법이 예제에 보이지 않음

### ISSUE THREAD

**Issue by redjade** [tbai2019/HanBert-54k-N#3]
안녕하세요.

moran의 동적 라이브러리와 DB를 별도 디렉토리에 옮겨서 테스트를 해보니, 예제대로 기능어인 경우에 대한 토큰이 나오지 않고 주로 wordpiece 스타일의 토큰이 나왔습니다.  `moran.db`를 `/usr/local/moran/moran.db`에 설치하면 예제와 동일한 결과를 얻었습니다. 즉, 설명과 달리 `moran.db`의 파일 경로를 수정할 수 없거나, 수정 방법이 예제에 보이지 않습니다. 제가 못 찾은 것일 수도 있으니, 혹시 수정 방법이 있다면 알려주시길 부탁드립니다.

테스트 결과는 이렇습니다. `strings`로 `libmoran4dnlp.so`의 문자열을 살펴보니 `moran.db`, `udict.txt`, `uentity.txt` 모두에 대해 `/usr/local/moran` 디렉토리 아래의 절대 경로가 보입니다. `MorAn16_open_dbs`의 경우, 별도의 경로 파라미터를 받는지 잘 모르겠습니다. 시험삼아 변경된 파일의 절대 경로, 변경된 디렉토리의 절대 경로, 상대 경로 등을 테스트했고, `/usr/local/moran`에 해당 DB 파일이 있는 경우를 제외하고 모두 `-1`을 돌려줬습니다(로딩되지 않았습니다).

테스트는 [HanBert 공개 포스트](https://twoblockai.com/2020/01/22/hanbert%eb%a5%bc-%ea%b3%b5%ea%b0%9c%ed%95%a9%eb%8b%88%eb%8b%a4/)의 [다운로드 링크](https://drive.google.com/file/d/1mNDA-SNCsnu60wzKVe_Y3k-dq3LoDHB2/view?usp=sharing)를 오늘(2020.05.06) 다운로드하여 진행했습니다.

따라서 [Moran (한국어 문장을 Deep NLP용 한국어 표현으로 변환) 예제](https://github.com/tbai2019/HanBert-54k-N#moran-%ED%95%9C%EA%B5%AD%EC%96%B4-%EB%AC%B8%EC%9E%A5%EC%9D%84-deep-nlp%EC%9A%A9-%ED%95%9C%EA%B5%AD%EC%96%B4-%ED%91%9C%ED%98%84%EC%9C%BC%EB%A1%9C-%EB%B3%80%ED%99%98-%EC%98%88%EC%A0%9C) 부분의 다음 내용은 수정이 필요합니다.

수정 전
> moran.py의 소스코드에서 해당 DB와 so의 위치를 수정하실 수 있습니다.

수정 후 : `moran.db` 경로를 변경할 수 있는 방법이 *없는* 경우, DB 파일의 절대 경로를 안내
> moran.py의 소스코드에서 so의 위치를 수정하실 수 있습니다. 그러나 db 파일은 꼭 `/usr/local/moran/moran.db`에 설치되어야 합니다.

수정 후 : `moran.db` 경로를 변경할 수 있는 방법이 *있는* 경우, 변경된 `moran.py` 및 관련 동적 라이브러리 배포

감사합니다.

**Comment by tbai2019** [comment]
네 맞는 말씀이네요. 
현재 배포한 libmoran4dnlp.so는 moran.db 경로를 변경할 수 있는 방법이 없는 라이브러리입니다. 
내용을 수정하겠습니다.
